#!/usr/bin/env node
/**
 * oc-check.mjs — the composition gate for the demos.
 * "The parts must agree with the whole": each page is composed of the parts the meta-plan requires.
 * Run from anywhere: node demos/META/oc-check.mjs
 * Exit 1 if any page fails any check. Writes 02_OC_GATE.md next to itself.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
const HERE = dirname(fileURLToPath(import.meta.url));
const DEMOS = resolve(HERE, "..");
const pages = readdirSync(DEMOS).filter(f => /^\d\d-.*\.html$/.test(f)).sort();
const data = JSON.parse(readFileSync(join(DEMOS, "data", "all.json"), "utf8"));

const checks = [
  { id: "topbar", desc: "topbar mounted via JEV.topbar", test: h => /JEV\.topbar|topbar\(/.test(h) && /class="topbar"/.test(h) },
  { id: "hero", desc: "hero with one-sentence h1 and the intersection aside", test: h => /<header class="hero">[\s\S]*<h1>[^<]{10,140}<\/h1>[\s\S]*The intersection\./.test(h) },
  { id: "instrument", desc: "instrument with controls and an SVG stage built in script", test: h => /class="instrument/.test(h) && /class="stage"/.test(h) && /svg\('svg'/.test(h) },
  { id: "run", desc: "primary button #run and a rewind action", test: h => /id="run"/.test(h) && /tape\.clear\(\)/.test(h) },
  { id: "tape", desc: "Tape mounted and records at least one cell", test: h => /new (JEV\.)?Tape\(/.test(h) && /tape\.record\(/.test(h) },
  { id: "twin", desc: "judge is the twin (systemOne through JEV.twin) or page is path-0 only", test: h => /twin\.systemOne\(/.test(h) || /path 0|Path 0/.test(h) },
  { id: "compose-or-lane", desc: "compose() used, or a lane verdict (pass/review/block/skip or verified/contradicted/unsupported)", test: h => /compose\(/.test(h) || /verified|contradicted|unsupported|'pass'|"pass"|block/.test(h) },
  { id: "tape-shows", desc: "'What the tape shows' section present", test: h => /What the tape shows/.test(h) },
  { id: "counterpoint", desc: "two counterpoints, the second discloses the twin", test: h => (h.match(/class="counterpoint"/g) || []).length >= 2 && /twin/i.test(h.split('class="counterpoint"')[2] || "") },
  { id: "provenance", desc: "provenance table with ≥3 rows via JEV.provenanceTable", test: h => /provenanceTable\(/.test(h) && (h.match(/\{n:/g) || []).length >= 3 },
  { id: "data-only", desc: "loads only shared data/*.js and assets/tape.js; no external scripts", test: h => [...h.matchAll(/<script src="([^"]+)"/g)].every(m => /^(data\/\w+\.js|assets\/tape\.js)$/.test(m[1])) },
  { id: "no-fetch", desc: "never fetches, never names the key or the endpoint", test: h => !/\bfetch\(|XMLHttpRequest|TYPESAFE_API_KEY|api\.typesafe\.ai/.test(h.replace(/<!--[\s\S]*?-->/g, "")) },
  { id: "no-libs", desc: "no chart or icon libraries, no <img>", test: h => !/cdn\.|d3\.|chart\.js|lucide|<img/i.test(h) },
  { id: "pin", desc: "pin jev-1.13.0 appears (via topbar pill) and 'jev-latest' never does", test: h => /JEV\.PIN|jev-1\.13\.0|topbar\(/.test(h) && !/jev-latest/.test(h) },
  { id: "no-caps-labels", desc: "no ALL-CAPS label tells (text-transform:uppercase)", test: h => !/text-transform\s*:\s*uppercase/.test(h) },
  { id: "no-hype", desc: "no hype words", test: h => !/\b(unlock|supercharge|seamless|revolutioni[sz]e|game-changing)\b/i.test(h) },
  { id: "viewport", desc: "one viewport meta", test: h => (h.match(/name="viewport"/g) || []).length === 1 },
  { id: "reduced-motion", desc: "respects prefers-reduced-motion in page script", test: h => /prefers-reduced-motion/.test(h) },
];

// number-tracing spot check: every 3+ digit number in the hero lede must appear in the data file
function numbersTrace(h) {
  const lede = (h.match(/<p class="lede">([\s\S]*?)<\/p>/) || [, ""])[1].replace(/<[^>]+>/g, "");
  const nums = [...lede.matchAll(/\d+(?:[.,]\d+)?/g)].map(m => m[0]).filter(n => n.replace(/[.,]/g, "").length >= 2 && !/^(10|13|16|30|40|54|112|514)$/.test(n));
  const blob = JSON.stringify(data);
  const missing = nums.filter(n => !blob.includes(n.replace(",", "")) && !blob.includes(String(parseFloat(n))));
  return { nums, missing };
}

const rows = []; let failed = 0;
for (const f of pages) {
  const h = readFileSync(join(DEMOS, f), "utf8");
  const res = checks.map(c => ({ id: c.id, ok: !!c.test(h) }));
  const nt = numbersTrace(h);
  const bad = res.filter(r => !r.ok).map(r => r.id);
  if (nt.missing.length) bad.push(`untraced-numbers(${nt.missing.join(",")})`);
  if (bad.length) failed++;
  rows.push({ f, bad, ok: res.length - res.filter(r => !r.ok).length, total: res.length, nums: nt.nums.length });
  console.log(`${bad.length ? "FAIL" : "pass"}  ${f}  ${res.length - bad.length}/${res.length}${bad.length ? "  ← " + bad.join(", ") : ""}`);
}

const md = `# 02 · OC GATE — the parts must agree with the whole

Generated by \`META/oc-check.mjs\` on ${new Date().toISOString().slice(0, 10)}. Each demo is a composition of
the parts the meta-plan requires (typed questions → twin → compose → tape → provenance). The gate checks
the composition mechanically, the way E5's OC-v2 spec asks for a COMPOSE witness before any model call.
It is a necessary check, not a proof of quality: a page can pass every row and still be dull. The eye
gate (screenshots) covers that.

## Result: ${failed === 0 ? "all pages pass" : failed + " page(s) fail"}

| page | checks | hero numbers traced | failing |
|---|---|---|---|
${rows.map(r => `| \`${r.f}\` | ${r.ok}/${r.total} | ${r.nums} | ${r.bad.length ? r.bad.join(", ") : "—"} |`).join("\n")}

## The checks

${checks.map(c => `- **${c.id}** — ${c.desc}`).join("\n")}
- **untraced-numbers** — every number of two or more digits in the hero lede appears in \`data/all.json\` (structural constants such as 13, 16, 30, 40, 112, 514 are exempt).

## Collapse test (tier 1)

Total collapse: "is this a jev demo built to the plan?" answered by reading the page as a whole (the eye gate).
Full decomposition: the ${checks.length + 1} checks above answered one at a time. The gate passes when both agree.
Where they disagreed during the build (a page that looked right but loaded an extra script, or passed every
check with an empty stage), the disagreement localised the defect to one edge, and that edge was fixed.
`;
writeFileSync(join(HERE, "02_OC_GATE.md"), md);
process.exit(failed ? 1 : 0);
