#!/usr/bin/env node
/**
 * record.mjs — record REAL TypeSafe answers for the demos, once, on your machine.
 *
 * The pages ship a deterministic twin. This script replaces the twin's answers with recorded
 * answers from POST https://api.typesafe.ai/v1/systemone, pinned to jev-1.13.0, following the
 * tape's own rule: record once, replay forever, never re-POST on replay.
 *
 * How it works: it opens each demo headlessly, clicks the primary button in its default state,
 * collects the exact requests the page built (window.__jevRequests), POSTs each one for real,
 * and writes demos/data/recorded.js keyed by a stable hash of (model, state, questions). When a
 * page later builds the same request, JEV.twin.systemOne returns the recorded map and the
 * top-bar pill turns green ("recorded TypeSafe answers · <date>").
 *
 *   cp .env.example .env && edit          # key stays on this machine
 *   set -a && source .env && set +a
 *   node demos/record.mjs                 # all demos, default state
 *   node demos/record.mjs 04 06 07        # only these
 *   node demos/record.mjs --dry           # collect and print requests, POST nothing
 *
 * Fail closed: no key → exit 1, nothing written. Never prints the key. Never sends mail or pushes.
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const dry = args.includes("--dry");
const only = args.filter(a => /^\d\d$/.test(a));
const key = process.env.TYPESAFE_API_KEY;
const PIN = process.env.TYPESAFE_DEFAULT_MODEL || "jev-1.13.0";
const BASE = process.env.TYPESAFE_BASE_URL || "https://api.typesafe.ai";
if (PIN !== "jev-1.13.0") { console.error(`refusing: model must be pinned to jev-1.13.0, got ${PIN}`); process.exit(1); }
if (!key && !dry) { console.error("TYPESAFE_API_KEY is not set. Copy .env.example → .env on this machine. Nothing recorded."); process.exit(1); }

let chromium;
try { ({ chromium } = await import("playwright")); }
catch { try { ({ chromium } = await import("/opt/node22/lib/node_modules/playwright/index.mjs")); } catch { console.error("playwright not found: npm i -D playwright (and npx playwright install chromium)"); process.exit(1); } }

const pages = readdirSync(HERE).filter(f => /^\d\d-.*\.html$/.test(f) && (!only.length || only.includes(f.slice(0, 2)))).sort();
const outPath = join(HERE, "data", "recorded.js");
const prior = existsSync(outPath) ? JSON.parse(readFileSync(outPath, "utf8").replace(/^[\s\S]*?=\s*/, "").replace(/;\s*$/, "")) : { answers: {} };
const recorded = { pin: PIN, endpoint: `${BASE}/v1/systemone`, answers: { ...prior.answers }, pages: { ...(prior.pages || {}) } };

const browser = await chromium.launch({ executablePath: process.env.CHROMIUM || undefined, args: ["--no-sandbox"] });
let posts = 0, reused = 0;
for (const f of pages) {
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  await page.goto("file://" + resolve(HERE, f), { waitUntil: "load" });
  await page.evaluate(() => { window.JEV_DATA.recorded = null; window.__jevRequests = []; });   // force the page to build fresh requests
  const btn = await page.$("#run");
  if (btn) { await btn.click(); await page.waitForTimeout(3500); }
  const reqs = await page.evaluate(() => (window.__jevRequests || []));
  await page.close();
  console.log(`${f}: ${reqs.length} request(s)`);
  for (const { key: k, req } of reqs) {
    if (recorded.answers[k]) { reused++; console.log(`  ${k} already recorded (${Object.keys(recorded.answers[k].answers).length} answers) — replayed, not re-POSTed`); continue; }
    if (dry) { console.log(`  ${k} ${Object.keys(req.questions).length} questions (dry run)`); continue; }
    const res = await fetch(`${BASE}/v1/systemone`, { method: "POST", headers: { authorization: `Bearer ${key}`, "content-type": "application/json" }, body: JSON.stringify(req) });
    const text = await res.text();
    if (!res.ok) { console.error(`  ${k} TypeSafe ${res.status}: ${text.slice(0, 300)}`); if (res.status === 401 || res.status === 422) process.exit(2); continue; }
    const body = JSON.parse(text);
    if (body.model !== "jev-1.13.0") { console.error(`  ${k} response.model=${body.model} ≠ jev-1.13.0 — not recorded (non-retryable per spec/TEMPORAL.md)`); continue; }
    posts++;
    recorded.answers[k] = { model: body.model, answers: body.answers, usage: body.usage, at: new Date().toISOString(), page: f, n: Object.keys(req.questions).length };
    recorded.pages[f] = (recorded.pages[f] || []).concat(k);
    console.log(`  ${k} recorded: ${Object.keys(body.answers).length} answers, usage in=${body.usage?.input_tokens} out=${body.usage?.output_tokens}`);
  }
}
await browser.close();
if (!dry) {
  writeFileSync(outPath, `// generated by demos/record.mjs — real TypeSafe answers, recorded once, replayed by the pages\nwindow.JEV_DATA=window.JEV_DATA||{};window.JEV_DATA.recorded=${JSON.stringify(recorded)};\n`);
  console.log(`\n${posts} POST(s) made, ${reused} reused. Wrote ${outPath}. Commit it: the pages will replay these answers and show a green pill.`);
} else console.log(`\ndry run: 0 POSTs.`);
